### ISSUE TITLE
Push Hash

### ISSUE THREAD

**Issue by CHC-Griff** [mohlcyber/OpenDXL-Phantom#3]
Hello Martin,

We started with version 1.2 of your application and found the push hash to McAfee a useful option.  Seems it was removed at some point.  Can that be restored?  I'm happy to assist in restoring that function in the app if you're looking for a collaborator. 
Thanks,
Josh

**Comment by mohlcyber** [comment]
Hi Josh, 
thanks for you message. The push hash function got renamed in 1.2.3 to set reputation. 
With the set reputation action you will be able to set TIE enterprise reputations. 
Is that the action you were looking for?
All the best,
Martin

**Comment by mohlcyber** [comment]
Hi Josh,
i will close the open issue. Please reopen if there is anything with the set reputation action.
Many thanks and all the best,
Martin
