### ISSUE TITLE
Set reputation readonly status

### ISSUE THREAD

**Issue by seansean-dev** [mohlcyber/OpenDXL-Phantom#4]
Hi,

Should the set reputation readOnly be set to false?
This is so we can have approval set on the asset.

Thanks

**Comment by mohlcyber** [comment]
Hi,
great idea. I just made the change to the newest released app v.1.2.9.
Thanks for the input. Please let me know if this fixed the issue.

All the best,
Martin

**Comment by mohlcyber** [comment]
I will close the issue for now. If there are any issues please reopen.
